cugos/cugos.github.com

meetings/_posts/2015-02-18-cugos_monthly.markdown
=> talk: Field Papers or something

meetings/_posts/2015-02-18-cugos_monthly.markdown
Screwed this up the first time around.  Also, since we're using `@`s, may as well use my handle.
=> Markdown syntax

_layouts/event.html, css/site.css
* Adding image credit space for the header
=> image credit for mapbox

meetings/_posts/2015-04-15-cugos_monthly.markdown
I think it might be around 20 minutes.
=> Add Fred's talk to the agenda for 2015-04-15

2015-spring-fling/index.md, _layouts/event.html, css/site.css
* New `.schedule` layout for meetings, makes things a bit more malleable for different speaking types
* adding some basic talk information, but all still very "lorem ipsum"
This is not ready to merge!
=> Schedule updates

people/_posts/0000-01-01-aaron_racicot.markdown, people/_posts/0000-01-02-allison_bailey.markdown, people/_posts/0000-01-03-jared_erickson.markdown, people/_posts/1814-11-19-luke_bergmann.markdown, people/_posts/2013-04-28-matt-kenny.markdown, people/_posts/2013-05-27-greg_corradini.markdown, people/_posts/2014-05-05-dane_springmeyer.markdown, people/_posts/2014-08-10-sam-matthews.markdown, people/_posts/2014-08-16-ryan_small.markdown, people/_posts/2014-08-20-andrew_powers.markdown, people/_posts/2014-09-18-jacob_lesser.markdown, people/_posts/2014-10-16-debbie_bull.markdown, people/_posts/2014-10-22-Jonny_Kemp.markdown, people/_posts/2014-10-30-Paul_McCombs.markdown, people/_posts/2014-10-30-Peter_Keum.markdown, people/_posts/2014-10-30-anthony_lukach.markdown, people/_posts/2014-11-04-Josh_Jones.markdown, people/_posts/2014-11-19-david_shean.markdown, people/_posts/2014-11-19-julie-goldberg.markdown, people/_posts/2014-11-19-mary-solbrig.markdown, people/_posts/2014-11-19-matt-stevenson.markdown, people/_posts/2014-11-19-nicholas_hallahan.md, people/_posts/2014-11-19-russ-frizzell.markdown, people/_posts/2014-11-20-Matt_Dunbar.markdown, people/_posts/2014-11-20-bitnerd.markdown, people/_posts/2014-11-20-derek-huling.markdown, people/index.html, static/css/site.css, static/js/site.js
Updating the people page to be less janky
=> People update

people/_posts/2015-06-17-eldan_goldenberg.markdown
=> Adding myself

people/_posts/0000-01-01-chris_beddow.markdown
=> adding myself here I am

people/_posts/2015-07-10-john-tuthill.markdown
I heard you are in to maps, so I am adding myself to your group.
=> Adding myself.

meetings/_posts/2015-08-19-cugos_monthly.markdown
A little description for a talk I want to give next week.
=> Adding a talk for Aug 19.

meetings/_posts/2015-12-16-cugos_monthly.markdown
=> adding self to schedule

meetings/_posts/2016-02-17-cugos_monthly.markdown
=> Add npeihl to 2016-02-17

people/_posts/2016-05-09-ben-hudson.markdown
Never miss the chance to make a good first impression...
=> wow, somehow managed a typo in the path to my github page

_includes/mailing-list.html, _layouts/default.html, _layouts/home.html, _layouts/meetings.html, static/css/site.css
Working on our last open issue! This is below the navigation on every page. It's a _little_ obnoxious, but should get some folks signed up.
cc @powersa @aaronr @foundatron
=> site-wide mailing list notification

meetings/_posts/2016-11-16-cugos_monthly.markdown
Andrew suggested I give a update.
=> added myself/GeoHackWeek to agenda

_includes/nav.html, static/css/site.css, static/js/site.js
Making the nav bigger, stronger, faster...
=> bigger nav

next/index.html
A URI that always takes you to the upcoming meeting... 
```
cugos.org/next
```
cc @powersa
=> permalink to upcoming meeting

meetings/_posts/2017-01-18-cugos_monthly.markdown
This is a brief description of a proposed talk for the next CUGOS meeting.
=> Proposal for 2017-01-18 talk

meetings/_posts/2017-01-18-cugos_monthly.markdown
Will help people find the resources that various lovely CUGOSians suggested
=> Added links from my notes

notes/_posts/2017-02-13-notes.md
cc @aaronr @thedeb @powersa @foundatron
=> Board notes, 02/13/2017

meetings/_posts/2017-03-15-cugos_monthly.md
=> Proposing a quick talk

meetings/_posts/2017-04-19-cugos_monthly.md
Hey I'm new to the group, and Greg(junkmob) asked me to present a recent project.
=> april meeting and gerrypy

2017-spring-fling/index.md
Added detailed workshop descriptions with target audience and preparations expected, including links to resources.
=> Cugos 2017deb

meetings/_posts/2017-12-13-cugos_monthly.md
=> Added Jason T. to agenda.

people/_posts/2018-04-11-stephen-mangum.markdown
=> added myself

meetings/_posts/2018-05-16-cugos_monthly.md
Post notes to 2018-05-16 Meeting, edited with Debbie Bull.
Quick copy/paste and minimal editing/spelling fixes. Not sure how the formatting will transfer...
=> Add notes to 2018-05-16 Meeting

meetings/_posts/2018-07-18-cugos_monthly.markdown
Canceled other request and added more info about the topics.
=> Add jmt2080ad to agenda.

meetings/_posts/2018-09-19-cugos_monthly.md
Here are my notes from the September 19 CUGOS meeting. I know Debbie also has some notes. You may not want to merge this directly. 
Paul
=> Paul's notes for 9/19/2018

people/_posts/2018-11-10-ranek_kiil.markdown
Apparently I'm one of just a few CUGOS members with a five-digit GitHub ID. :)
=> Add @ranek

meetings/_posts/2019-05-15-cugos_monthly.md
=> Adding myself to the May agenda

meetings/_posts/2019-06-19-cugos_monthly.md
Hello, I'd love to talk about a project I've been working on called [Observe](https://github.com/developmentseed/observe) at the June 19 meeting.
=> add observe talk for june 19 meeting

meetings/_posts/2020-03-18-cugos_monthly.md
initial meeting post for march 18
=> March 18 meeting post

index.md
Closes https://github.com/cugos/cugos.github.com/issues/268
=> Fix Google Group feed on home page

meetings/_posts/2020-05-20-cugos_monthly.md
=> adds me (geografa) to list

meetings/_posts/2021-10-20-cugos_monthly.md
=> Add Oct 2021

meetings/_posts/2022-01-19-cugos_monthly.md
=> Add Scott Shawcroft to January 2022 agenda

meetings/_posts/2024-03-20-cugos_monthly.md
Adding a talk for March meetup, need to create entirely new meeting?
=> Create March Meetu

people/_posts/2025-02-20-tim-johns.markdown
=> Added Tim Johns
